[theme]
primaryColor = "#6A8EAE"                 # Darker pastel blue for primary elements
backgroundColor = "#E6F0F5"              # Light pastel blue for the background
secondaryBackgroundColor = "#A3B8CC"     # Medium pastel blue for secondary areas
textColor = "#2C3E50"                   # Darker blue for text to ensure readability
font = "sans serif"
