[theme]
primaryColor = "#A7C080"                 # Soft pastel green for primary elements (buttons, highlights)
backgroundColor = "#2D353B"              # Dark grayish-green background
secondaryBackgroundColor = "#3A454A"     # Slightly lighter grayish-green for contrast sections
textColor = "#D3C6AA"                   # Warm off-white for text
font = "sans serif"
